// Generated by <%= pkg.name %> <%= pkg.version %>
'use strict';

// # Globbing
// for performance reasons we're only matching one level down:
// 'test/spec/{,*/}*.js'
// If you want to recursively match all subfolders, use:
// 'test/spec/**/*.js'

module.exports = function (grunt) {

  // Time how long tasks take. Can help when optimizing build times
  require('time-grunt')(grunt);

  // Load grunt tasks automatically
  require('load-grunt-tasks')(grunt);

  // Configurable paths
  var config = {
    proj: '<%= projName %>',
    host: '<%= host %>',
    port: <%= port %>,
    cssDir: '<%= cssDir %>',
    sassDir: '<%= sassDir %>',
    jsDir: '<%= jsDir %>',
    jsLibDir: '<%= jsLibDir %>',
    bowerDir: '<%= bowerDir %>',
    bowerDirName: require('path').basename('<%= bowerDir %>'),
    imgDir: '<%= imgDir %>',
    fontsDir: '<%= fontsDir %>',
    vsVer: '<%= vsVer %>'<% if (includeNode) { %>,
    nodeHost: 'localhost',
    nodePort: 9000,
    nodeStartPath: '<%= nodeStartPath %>'<% } %>
  };

  // Define the configuration for all the tasks
  grunt.initConfig({

    // Project settings
    config: config,

    // Watches files for changes and runs tasks based on the changed files
    watch: {
      options: {
        nospawn: true
      },
      js: {
        files: ['<%%= config.jsDir %>/{,*/}*.js'],
        tasks: ['jshint']
      },
      bower: {
        files: ['bower.json'],
        tasks: ['install:bower', 'bower:require']
      },
      sass: {
        files: ['<%%= config.sassDir %>/{,*/}*.{scss,sass}'],
        tasks: ['sass', 'autoprefixer'],
        options: {
          livereload: true
        }
      },
      reload: {
        options: {
          livereload: 35729
        },
        files: [
            'Gruntfile.js',
            'Views/**/*.cshtml',
            '<%%= config.cssDir %>/{,*/}*.css',
            '<%%= config.jsDir %>/{,*/}*.js',
            '<%%= config.imgDir %>/{,*/}*.{gif,jpeg,jpg,png,svg,webp}'
        ]
      }
    },<% if (includeNode) { %>

    // The actual grunt server settings
    connect: {
      options: {
        port: '<%%= config.nodePort %>',
        open: 'http://<%%= config.nodeHost %>:<%%= config.nodePort %><%%= config.nodeStartPath %>',
        livereload: 35729,
        // Change this to '0.0.0.0' to access the server from outside
        hostname: '<%%= config.nodeHost %>'
      },
      livereload: {
        options: {
          middleware: function(connect) {
            return [
              connect.static('.')
            ];
          }
        }
      },
    },<% } %>

    // Empties files/dirs to start fresh
    clean: {
      dist: [
          'min'
      ]
    },

    // Make sure code styles are up to par and there are no obvious mistakes
    jshint: {
      options: {
        jshintrc: '.jshintrc',
        reporter: require('jshint-stylish')
      },
      all: [
          'Gruntfile.js',
          '<%%= config.jsDir %>/*.js',
          '!<%%= config.jsLibDir %>/*'
      ]
    },

    // Compiles Sass to CSS and generates necessary files if requested
    sass: {
      options: {
        sourceMap: true,
        includePaths: ['<%%= config.bowerDir %>']
      },
      dist: {
        files: [{
          expand: true,
          cwd: '<%%= config.sassDir %>',
          src: ['*.{scss,sass}'],
          dest: '<%%= config.cssDir %>',
          ext: '.css'
        }]
      }
    },

    // Add vendor prefixed styles
    autoprefixer: {
      options: {
        browsers: ['> 1%', 'last 2 versions', 'Firefox ESR', 'Opera 12.1']
      },
      dist: {
        files: [{
          expand: true,
          cwd: '<%%= config.cssDir %>',
          src: '{,*/}*.css',
          dest: '<%%= config.cssDir %>'
        }]
      }
    },

    // Copy files to places other tasks can use
    copy: {
      dist: {
        src: 'Views/Shared/_Layout.cshtml',
        dest: 'min/'
      }
    },

    // The following *-min tasks produce minified files in the dist folder
    imagemin: {
      dist: {
        files: [{
          expand: true,
          cwd: '<%%= config.imgDir %>',
          src: '{,*/}*.{gif,jpeg,jpg,png}',
          dest: 'min/<%%= config.imgDir %>'
        }]
      }
    },
    svgmin: {
      dist: {
        files: [{
          expand: true,
          cwd: '<%%= config.imgDir %>',
          src: '{,*/}*.svg',
          dest: 'min/<%%= config.imgDir %>'
        }]
      }
    },
    cssmin: {
      dist: {
        options: {
          keepSpecialComments: 0
        },
        files: {
          'min/<%%= config.cssDir %>/min.css': [
              '<%%= config.cssDir %>/{,*/}*.css',
              '!<%%= config.cssDir %>/{,*/}*.min.css'
          ]
        }
      }
    },
    uglify: {
      dist: {
        files: {
          'min/<%%= config.jsDir %>/min.almond.js': [
              '<%%= config.bowerDir %>/almond/almond.js'
          ]
        }
      }
    },
    bower: {
      require: {
        rjsConfig: '<%%= config.jsDir %>/config.js',
        options: {
          baseUrl: '<%%= config.jsDir %>'
        }
      }
    },
    requirejs: {
      compile: {
        options: {
          baseUrl: '<%%= config.jsDir %>',
          mainConfigFile: '<%%= config.jsDir %>/config.js',
          name: 'main',
          out: 'min/<%%= config.jsDir %>/min.js',
          paths: {
            'jquery': 'empty:'
          },
          preserveLicenseComments: false
        }
      }
    },
    rev: {
      dist: {
        files: {
          src: [
              'min/<%%= config.cssDir %>/{,*/}*.css',
              'min/<%%= config.jsDir %>/{,*/}*.js',
              'min/<%%= config.imgDir %>/{,*/}*.*'
          ]
        }
      }
    },
    usemin: {
      options: {
        assetsDirs: ['min']
      },
      html: ['min/Views/Shared/_Layout.cshtml'],
      css: ['min/<%%= config.cssDir %>/{,*/}*.css']
    },
    cdnify: {
      dist: {
        options: {
          localFallback: true,
          bowerDir: '<%%= config.bowerDir %>',
        },
        html: ['min/Views/Shared/_Layout.cshtml'],
        almond: '<%%= config.jsDir %>/min.almond.js',
        components: {
          'jquery': {
            localPath: '<%%= config.bowerDir %>/jquery/dist/jquery.min.js',
            success: 'window.jQuery'
          }
        }
      }
    },

    install: {
      bower: {}
    },

    // Open in browser
    open: {
      server: {
        path: 'http://<%%= config.host %>:<%%= config.port %>',
        app: 'chrome'
      }
    }
  });

  grunt.registerTask('install', 'install/restore npm and bower dependencies', function(cmd) {
    var exec = require('child_process').exec;
    var done = this.async();
    exec(cmd + ' install', {cwd: '.'}, function(err, stdout/*, stderr */) {
      console.log(stdout);
      done();
    });
  });
  <% if (includeNode) { %>
  grunt.registerTask('serve', function (server) {
    if (server === 'node') {
      return grunt.task.run([
        'connect:livereload',
        'watch'
      ]);
    }

    grunt.task.run([
      'open:server',
      'watch'
    ]);
  });<% } else { %>
  grunt.registerTask('serve', [
    'open:server',
    'watch'
  ]);<% } %>

  grunt.registerTask('build', function (target) {
    if (target === 'dist') {
      return grunt.task.run([
          'clean:dist',
          'copy:dist',
          'install:bower',
          'bower:require',
          'sass',
          'autoprefixer',
          'requirejs',
          'cssmin',
          'uglify',
          'imagemin',
          'svgmin',
          'cdnify',
          'rev',
          'usemin'
      ]);
    }

    grunt.task.run([
        'install:bower',
        'bower:require',
        'sass',
        'autoprefixer'
    ]);
  });

  grunt.registerTask('default', [
      'newer:jshint',
      'build'
  ]);
};
